# This file will be generated by nixos-generate-config.
# Do not edit manually - run: nixos-generate-config --show-hardware-config > hardware.nix
{ config, lib, pkgs, ... }:

{
  # Placeholder - replace with output of nixos-generate-config
}
